# Generated by Django 2.2 on 2019-05-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankerCoreApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(max_length=255)),
                ('UserIDEncrypted', models.CharField(max_length=255)),
                ('PasswordBase64', models.CharField(max_length=255)),
                ('EncryptedPasswordEncoded', models.CharField(max_length=255)),
                ('LoginEmail', models.CharField(max_length=255)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Address2', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('ZipCode', models.CharField(max_length=255)),
                ('PhoneNumber', models.CharField(max_length=255)),
            ],
        ),
    ]
